#!/bin/bash
if ! which systemd > /dev/null; then
	echo "You don't have systemd installed, this won't work!"
	exit 1
fi
sudo cp gpuPower /usr/lib/systemd/scripts/
sudo cp gpuPower.service /usr/lib/systemd/system/
sudo systemctl enable gpuPower
echo 'All done!'
exit 0
